/**
 * Data layer for the Marquardt US Sensor report app.
 *
 * All JSON files in this directory are generated by `scripts/extract-data.mjs`.
 * Import from here — never import JSON files directly in UI code.
 *
 * Usage:
 *   import { product, ranking, markets } from "@/data";
 *   import { getMarket, getODI, listMarkets } from "@/data";
 */

import type {
  ProductDecomposition,
  FunctionalPromiseData,
  ConstraintsData,
  HomeMarketCompetition,
  MarketDiscovery,
  RankingData,
  SourcesRegistry,
  MarketIndexEntry,
  JTBDData,
  ODIData,
  ValueNetworkData,
  KanoData,
  CompatibilityData,
  AlternativesData,
  MarketMeta,
  BOMData,
} from "@/types";

// ─── Static JSON imports ──────────────────────────────────────────────────────

import _product from "./product.json";
import _functionalPromise from "./functionalPromise.json";
import _constraints from "./constraints.json";
import _homeMarket from "./homeMarketCompetition.json";
import _marketDiscovery from "./marketDiscovery.json";
import _ranking from "./ranking.json";
import _sources from "./sources.json";
import _marketsIndex from "./markets/index.json";

// ─── Market data imports — one per slug ───────────────────────────────────────

// finfish-farming
import _finfishMeta from "./markets/finfish-farming/meta.json";
import _finfishJtbd from "./markets/finfish-farming/jtbd.json";
import _finfishOdi from "./markets/finfish-farming/odi.json";
import _finfishVn from "./markets/finfish-farming/valueNetwork.json";
import _finfishKano from "./markets/finfish-farming/kano.json";
import _finfishCompat from "./markets/finfish-farming/compatibility.json";
import _finfishAlt from "./markets/finfish-farming/alternatives.json";

// hvac-contractors
import _hvacMeta from "./markets/hvac-contractors/meta.json";
import _hvacJtbd from "./markets/hvac-contractors/jtbd.json";
import _hvacOdi from "./markets/hvac-contractors/odi.json";
import _hvacVn from "./markets/hvac-contractors/valueNetwork.json";
import _hvacKano from "./markets/hvac-contractors/kano.json";
import _hvacCompat from "./markets/hvac-contractors/compatibility.json";
import _hvacAlt from "./markets/hvac-contractors/alternatives.json";

// district-energy
import _districtMeta from "./markets/district-energy/meta.json";
import _districtJtbd from "./markets/district-energy/jtbd.json";
import _districtOdi from "./markets/district-energy/odi.json";
import _districtVn from "./markets/district-energy/valueNetwork.json";
import _districtKano from "./markets/district-energy/kano.json";
import _districtCompat from "./markets/district-energy/compatibility.json";
import _districtAlt from "./markets/district-energy/alternatives.json";

// heating-equipment
import _heatingMeta from "./markets/heating-equipment/meta.json";
import _heatingJtbd from "./markets/heating-equipment/jtbd.json";
import _heatingOdi from "./markets/heating-equipment/odi.json";
import _heatingVn from "./markets/heating-equipment/valueNetwork.json";
import _heatingKano from "./markets/heating-equipment/kano.json";
import _heatingCompat from "./markets/heating-equipment/compatibility.json";
import _heatingAlt from "./markets/heating-equipment/alternatives.json";

// commercial-service-machinery
import _commercialMeta from "./markets/commercial-service-machinery/meta.json";
import _commercialJtbd from "./markets/commercial-service-machinery/jtbd.json";
import _commercialOdi from "./markets/commercial-service-machinery/odi.json";
import _commercialVn from "./markets/commercial-service-machinery/valueNetwork.json";
import _commercialKano from "./markets/commercial-service-machinery/kano.json";
import _commercialCompat from "./markets/commercial-service-machinery/compatibility.json";
import _commercialAlt from "./markets/commercial-service-machinery/alternatives.json";

// ac-home-heating
import _acMeta from "./markets/ac-home-heating/meta.json";
import _acJtbd from "./markets/ac-home-heating/jtbd.json";
import _acOdi from "./markets/ac-home-heating/odi.json";
import _acVn from "./markets/ac-home-heating/valueNetwork.json";
import _acKano from "./markets/ac-home-heating/kano.json";
import _acCompat from "./markets/ac-home-heating/compatibility.json";
import _acAlt from "./markets/ac-home-heating/alternatives.json";

// flowmeters-reference
import _flowmetersMeta from "./markets/flowmeters-reference/meta.json";
import _flowmetersJtbd from "./markets/flowmeters-reference/jtbd.json";
import _flowmetersOdi from "./markets/flowmeters-reference/odi.json";
import _flowmetersVn from "./markets/flowmeters-reference/valueNetwork.json";
import _flowmetersKano from "./markets/flowmeters-reference/kano.json";
import _flowmetersCompat from "./markets/flowmeters-reference/compatibility.json";
import _flowmetersAlt from "./markets/flowmeters-reference/alternatives.json";

// breweries
import _breweriesMeta from "./markets/breweries/meta.json";
import _breweriesJtbd from "./markets/breweries/jtbd.json";
import _breweriesOdi from "./markets/breweries/odi.json";
import _breweriesVn from "./markets/breweries/valueNetwork.json";
import _breweriesKano from "./markets/breweries/kano.json";
import _breweriesCompat from "./markets/breweries/compatibility.json";
import _breweriesAlt from "./markets/breweries/alternatives.json";

// data-processing-hosting
import _dataProcMeta from "./markets/data-processing-hosting/meta.json";
import _dataProcJtbd from "./markets/data-processing-hosting/jtbd.json";
import _dataProcOdi from "./markets/data-processing-hosting/odi.json";
import _dataProcVn from "./markets/data-processing-hosting/valueNetwork.json";
import _dataProcKano from "./markets/data-processing-hosting/kano.json";
import _dataProcCompat from "./markets/data-processing-hosting/compatibility.json";
import _dataProcAlt from "./markets/data-processing-hosting/alternatives.json";

// ─── BOM imports — one per market slug ───────────────────────────────────────
import _finfishBom from "./markets/finfish-farming/bom.json";
import _hvacBom from "./markets/hvac-contractors/bom.json";
import _districtBom from "./markets/district-energy/bom.json";
import _heatingBom from "./markets/heating-equipment/bom.json";
import _commercialBom from "./markets/commercial-service-machinery/bom.json";
import _acBom from "./markets/ac-home-heating/bom.json";
import _flowmetersBom from "./markets/flowmeters-reference/bom.json";
import _breweriesBom from "./markets/breweries/bom.json";
import _dataProcBom from "./markets/data-processing-hosting/bom.json";

// ─── Typed exports ────────────────────────────────────────────────────────────

export const product = _product as unknown as ProductDecomposition;
export const functionalPromise = _functionalPromise as unknown as FunctionalPromiseData;
export const constraints = _constraints as unknown as ConstraintsData;
export const homeMarket = _homeMarket as unknown as HomeMarketCompetition;
export const marketDiscovery = _marketDiscovery as unknown as MarketDiscovery;
export const ranking = _ranking as unknown as RankingData;
export const sources = _sources as unknown as SourcesRegistry;
export const marketsIndex = _marketsIndex as unknown as MarketIndexEntry[];

// ─── Per-market data bundles ──────────────────────────────────────────────────

export interface MarketBundle {
  meta: MarketMeta;
  jtbd: JTBDData;
  odi: ODIData;
  valueNetwork: ValueNetworkData;
  kano: KanoData;
  compatibility: CompatibilityData;
  alternatives: AlternativesData;
  bom: BOMData;
}

const _marketBundles: Record<string, MarketBundle> = {
  "finfish-farming": {
    meta: _finfishMeta as unknown as MarketMeta,
    jtbd: _finfishJtbd as unknown as JTBDData,
    odi: _finfishOdi as unknown as ODIData,
    valueNetwork: _finfishVn as unknown as ValueNetworkData,
    kano: _finfishKano as unknown as KanoData,
    compatibility: _finfishCompat as unknown as CompatibilityData,
    alternatives: _finfishAlt as unknown as AlternativesData,
    bom: _finfishBom as unknown as BOMData,
  },
  "hvac-contractors": {
    meta: _hvacMeta as unknown as MarketMeta,
    jtbd: _hvacJtbd as unknown as JTBDData,
    odi: _hvacOdi as unknown as ODIData,
    valueNetwork: _hvacVn as unknown as ValueNetworkData,
    kano: _hvacKano as unknown as KanoData,
    compatibility: _hvacCompat as unknown as CompatibilityData,
    alternatives: _hvacAlt as unknown as AlternativesData,
    bom: _hvacBom as unknown as BOMData,
  },
  "district-energy": {
    meta: _districtMeta as unknown as MarketMeta,
    jtbd: _districtJtbd as unknown as JTBDData,
    odi: _districtOdi as unknown as ODIData,
    valueNetwork: _districtVn as unknown as ValueNetworkData,
    kano: _districtKano as unknown as KanoData,
    compatibility: _districtCompat as unknown as CompatibilityData,
    alternatives: _districtAlt as unknown as AlternativesData,
    bom: _districtBom as unknown as BOMData,
  },
  "heating-equipment": {
    meta: _heatingMeta as unknown as MarketMeta,
    jtbd: _heatingJtbd as unknown as JTBDData,
    odi: _heatingOdi as unknown as ODIData,
    valueNetwork: _heatingVn as unknown as ValueNetworkData,
    kano: _heatingKano as unknown as KanoData,
    compatibility: _heatingCompat as unknown as CompatibilityData,
    alternatives: _heatingAlt as unknown as AlternativesData,
    bom: _heatingBom as unknown as BOMData,
  },
  "commercial-service-machinery": {
    meta: _commercialMeta as unknown as MarketMeta,
    jtbd: _commercialJtbd as unknown as JTBDData,
    odi: _commercialOdi as unknown as ODIData,
    valueNetwork: _commercialVn as unknown as ValueNetworkData,
    kano: _commercialKano as unknown as KanoData,
    compatibility: _commercialCompat as unknown as CompatibilityData,
    alternatives: _commercialAlt as unknown as AlternativesData,
    bom: _commercialBom as unknown as BOMData,
  },
  "ac-home-heating": {
    meta: _acMeta as unknown as MarketMeta,
    jtbd: _acJtbd as unknown as JTBDData,
    odi: _acOdi as unknown as ODIData,
    valueNetwork: _acVn as unknown as ValueNetworkData,
    kano: _acKano as unknown as KanoData,
    compatibility: _acCompat as unknown as CompatibilityData,
    alternatives: _acAlt as unknown as AlternativesData,
    bom: _acBom as unknown as BOMData,
  },
  "flowmeters-reference": {
    meta: _flowmetersMeta as unknown as MarketMeta,
    jtbd: _flowmetersJtbd as unknown as JTBDData,
    odi: _flowmetersOdi as unknown as ODIData,
    valueNetwork: _flowmetersVn as unknown as ValueNetworkData,
    kano: _flowmetersKano as unknown as KanoData,
    compatibility: _flowmetersCompat as unknown as CompatibilityData,
    alternatives: _flowmetersAlt as unknown as AlternativesData,
    bom: _flowmetersBom as unknown as BOMData,
  },
  "breweries": {
    meta: _breweriesMeta as unknown as MarketMeta,
    jtbd: _breweriesJtbd as unknown as JTBDData,
    odi: _breweriesOdi as unknown as ODIData,
    valueNetwork: _breweriesVn as unknown as ValueNetworkData,
    kano: _breweriesKano as unknown as KanoData,
    compatibility: _breweriesCompat as unknown as CompatibilityData,
    alternatives: _breweriesAlt as unknown as AlternativesData,
    bom: _breweriesBom as unknown as BOMData,
  },
  "data-processing-hosting": {
    meta: _dataProcMeta as unknown as MarketMeta,
    jtbd: _dataProcJtbd as unknown as JTBDData,
    odi: _dataProcOdi as unknown as ODIData,
    valueNetwork: _dataProcVn as unknown as ValueNetworkData,
    kano: _dataProcKano as unknown as KanoData,
    compatibility: _dataProcCompat as unknown as CompatibilityData,
    alternatives: _dataProcAlt as unknown as AlternativesData,
    bom: _dataProcBom as unknown as BOMData,
  },
};

// Convenience alias: all bundles as a record
export const markets = _marketBundles;

// ─── Helper functions ─────────────────────────────────────────────────────────

/**
 * Return the full data bundle for a market slug.
 * Throws if the slug is not registered.
 */
export function getMarket(slug: string): MarketBundle {
  const bundle = _marketBundles[slug];
  if (!bundle) {
    throw new Error(
      `Unknown market slug: "${slug}". Available: ${Object.keys(_marketBundles).join(", ")}`
    );
  }
  return bundle;
}

/**
 * Return the ODI data for a market slug.
 */
export function getODI(slug: string): ODIData {
  return getMarket(slug).odi;
}

/**
 * Return the JTBD data for a market slug.
 */
export function getJTBD(slug: string): JTBDData {
  return getMarket(slug).jtbd;
}

/**
 * Return the Kano feature-fit data for a market slug.
 */
export function getKano(slug: string): KanoData {
  return getMarket(slug).kano;
}

/**
 * Return the value network data for a market slug.
 */
export function getValueNetwork(slug: string): ValueNetworkData {
  return getMarket(slug).valueNetwork;
}

/**
 * Return the compatibility assessment for a market slug.
 */
export function getCompatibility(slug: string): CompatibilityData {
  return getMarket(slug).compatibility;
}

/**
 * List all market index entries (ordered as in index.json).
 */
export function listMarkets(): MarketIndexEntry[] {
  return marketsIndex;
}

/**
 * List only new-market candidates (excludes the flowmeters reference entry).
 */
export function listNewMarkets(): MarketIndexEntry[] {
  return marketsIndex.filter((m) => !m.isReference);
}

/**
 * Return the meta record for a market slug.
 */
export function getMarketMeta(slug: string): MarketMeta {
  return getMarket(slug).meta;
}

/**
 * Return all ranked markets sorted by composite score descending.
 */
export function getRankedMarkets() {
  return [...ranking.rankedMarkets].sort(
    (a, b) => b.scores.composite - a.scores.composite
  );
}

/**
 * Look up a source by its prefixed ID (e.g. "PROD-S01").
 */
export function getSource(prefixedId: string): import("@/types").Source | undefined {
  return (sources as SourcesRegistry)[prefixedId];
}

/**
 * Return the Bill of Materials data for a market slug.
 */
export function getBOM(slug: string): BOMData {
  return getMarket(slug).bom;
}
